In [35]:
import numpy as np
np.set_printoptions(precision=8, suppress=True)

def primal_afffine(A,b,c,x, iterations = 15, epsilon = 1):

  iteration = 0

  X = np.diag(x)

  lamda_0 = np.linalg.inv(A @ X**2 @ A.T) @ A @ X**2 @ c

  while (c.T @ x - b.T @ lamda_0) > epsilon:
    d = -(np.eye(len(x))- X @ A.T @ np.linalg.inv(A @ X**2 @ A.T) @ A @ X) @ X @ c

    if np.all(d >= 0): print('Problem is unbounded')
    negative_ratios = [-1 / value for value in d if value < 0]
    min_ratio = min(negative_ratios)
    alpha = 0.99*min_ratio

    x = X @ (np.ones(len(d)) + alpha*d)
    X = np.diag(x)

    lamda_0 = np.linalg.inv(A @ X**2 @ A.T) @ A @ X**2 @ c

    iteration += 1

    if iteration > iterations: return 'Max iterations reached'

  return x

In [36]:
#Intial guess as interior point
A = [
    [1, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 0, 1, 1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
]
A = np.array(A)

b = [300, 1000, 1900, 2700, 700, 700, 700, 700, 200, 200]
b = np.array(b)

c = [19, 16, 18, 15, 21, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
c = np.array(c)

x = np.array([650, 650, 600, 600, 150, 150, 350, 450, 300, 100, 50, 50, 100, 100, 50, 50])
print(A @ x - b)

[0 0 0 0 0 0 0 0 0 0]


In [37]:
print('final values for intial guess as interior point')
primal_afffine(A,b,c,x)

final values for intial guess as interior point


array([599.9867027 , 699.94583731, 699.98855305, 699.94239951,
         0.13330567,   0.00549446, 299.98670266, 300.06584532,
       100.05989278,   0.00229182, 100.01329735,   0.05416299,
         0.011447  ,   0.05760096, 199.86669433, 199.99450554])

In [38]:
#Intial guess not an interior point
A = [
    [1, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 0, 1, 1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
]
A = np.array(A)

b = [300, 1000, 1900, 2700, 700, 700, 700, 700, 200, 200]
b = np.array(b)

c = [19, 16, 18, 15, 21, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
c = np.array(c)

x = [700, 700, 700, 700, 200, 200, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100] #not interior point
x = np.array(x)

result = np.dot(A, x)

r = b - result

A_m = np.hstack((A, r.reshape(-1, 1)))

x_m = np.hstack((x, 1))

c_m = np.hstack((c, 10**5))

In [39]:
print('final values for intial guess not an interior point')
primal_afffine(A_m,b,c_m,x_m)

final values for intial guess not an interior point


array([600.00688248, 699.97569157, 699.98006386, 699.9990695 ,
         0.01791117,   0.02504838, 300.00669932, 300.00017976,
       100.00529182,   0.00442087,  99.99317888,   0.02436964,
         0.01999731,   0.00099285, 199.98214977, 199.97501256,
         0.00000061])